/* ============================================================
   SCENT — Contenuti bilingue (IT / EN)  →  export SCENT_CONTENT
   Fonti: scent-srl.it, pubblicazione Cancers 2020, rassegna stampa
   (Corriere della Sera, Il Resto del Carlino, Estense, Università di Ferrara).
   ============================================================ */
export const SCENT_CONTENT = {
  it: {
    langLabel: 'IT',
    altLang: 'EN',
    nav: {
      links: [
        { id: 'dispositivo', label: 'Dispositivo' },
        { id: 'tecnologia', label: 'Tecnologia' },
        { id: 'validazione', label: 'Validazione' },
        { id: 'premi', label: 'Premi' },
        { id: 'stampa', label: 'Stampa' },
        { id: 'team', label: 'Team' },
      ],
      cta: 'Richiedi una demo',
    },
    hero: {
      badges: ['CE Marked', 'Clinicamente validato', 'Brevettato IT · UK · DE'],
      kicker: 'Diagnostica oncologica non invasiva',
      titleA: 'Individuare prima.',
      titleB: 'Senza essere invasivi.',
      lead: 'SCENT A1 rileva la possibile presenza di tumore al colon-retto analizzando i biomarcatori gassosi di un campione di feci — grazie a sensori a semiconduttore nanostrutturati.',
      ctaPrimary: 'Richiedi una demo',
      ctaSecondary: 'Come funziona',
      imageCaption: 'Foto del dispositivo SCENT A1',
    },
    press: {
      kicker: 'Ne parlano',
      quote: 'Il «naso artificiale» inventato a Ferrara che aiuta la diagnosi e snellisce le liste d’attesa.',
      source: 'Corriere della Sera',
      date: 'Aprile 2025',
      lead: 'Il progetto nato all’Università di Ferrara è stato raccontato dalle principali testate nazionali e locali.',
      outlets: [
        { name: 'Corriere della Sera', title: 'Il «naso artificiale» inventato a Ferrara', tag: 'Cronaca · Apr 2025' },
        { name: 'Il Resto del Carlino', title: '«Ora c’è ScentA1 per prevenire in tempo»', tag: 'Ferrara · Nov 2019' },
        { name: 'Estense.com', title: '«Annusare» per prevenire: la frontiera contro il tumore al colon', tag: 'Apr 2025' },
        { name: 'Università di Ferrara', title: 'Primi in Italia a usare strumenti alternativi alla colonscopia', tag: 'Unife · Nov 2019' },
        { name: 'Il Sole 24 Ore', title: 'Premio Marzotto, vince l’idea di Scent', tag: 'Tecnologie · Nov 2015' },
        { name: 'la Repubblica · Bologna', title: 'Quel test che annusa i tumori nato all’Università di Ferrara', tag: 'Cronaca · Nov 2015' },
        { name: 'Corriere Innovazione', title: 'Test antitumorali: a Scent i 300mila euro del Premio Marzotto', tag: 'Innovazione · Nov 2015' },
        { name: 'La Stampa', title: 'I sensori hi-tech conquistano il Premio Marzotto', tag: 'Economia · Nov 2015' },
        { name: 'La Nuova Ferrara', title: 'Trecentomila euro a Scent, la start-up di Unife', tag: 'Ferrara · Dic 2015' },
        { name: 'inSalute News', title: 'Screening del cancro al colon-retto: test innovativo all’AOU di Ferrara', tag: 'Salute · Mag 2017' },
      ],
    },
    awards: {
      kicker: 'Riconoscimenti',
      title: 'Premiata fin dal primo giorno',
      lead: 'Dal lancio come start-up innovativa, SCENT è stata riconosciuta dai principali premi italiani per l’innovazione e l’imprenditoria.',
      highlight: {
        year: '2015',
        name: 'Premio Gaetano Marzotto',
        body: '1º premio · Milano',
        prize: '300.000 €',
        prizeLabel: 'di finanziamento all’innovazione',
        desc: 'SCENT vince il primo premio dell’edizione 2015 — “l’innovazione al centro della nuova impresa italiana” — con una dotazione da trecentomila euro.',
      },
      items: [
        { year: '2014', name: 'StartCup Emilia-Romagna', body: 'Vincitore · selezione PNI', note: '3 progetti su 140 ammessi al Premio Nazionale per l’Innovazione.' },
        { year: '2015', name: 'Una Nuova Idea d’Impresa', body: '1º premio · Imola', note: 'Migliore idea imprenditoriale dell’edizione 2015.' },
        { year: '2015', name: 'Franci@INNOVazione', body: 'Ambasciata di Francia', note: 'Premio Start-Up assegnato a Roma dall’Ambasciatrice di Francia.' },
        { year: '2015', name: 'INNOVAMI', body: 'Incubatore d’impresa', note: 'Riconoscimento per l’innovazione tecnologica.' },
        { year: '2016', name: 'CNA “Pensiero Innovativo”', body: 'Otto start-up ferraresi', note: 'Premiata tra gli esempi di creatività avanzata del territorio.' },
        { year: '2013', name: 'UnifeCup', body: 'Università di Ferrara', note: 'Business Plan Competition per nuove imprese ad alto contenuto tecnologico.' },
      ],
    },
    stats: {
      kicker: 'I numeri',
      items: [
        { value: '84,1%', label: 'Sensibilità', sub: 'coorte clinica validata' },
        { value: '82,4%', label: 'Specificità', sub: 'vs test del sangue occulto' },
        { value: '⅔', label: 'Falsi positivi identificati', sub: 'meno colonscopie inutili' },
        { value: '3', label: 'Brevetti', sub: 'Italia · Regno Unito · Germania' },
      ],
    },
    device: {
      kicker: 'Il dispositivo',
      title: 'Screening del colon-retto, ripensato',
      lead: 'Utilizzato in combinazione con il test immunochimico fecale (FIT), SCENT A1 identifica i due terzi dei falsi positivi — riducendo le colonscopie non necessarie sui pazienti sani.',
      features: [
        { t: 'Portatile e semplice', d: 'Strumento compatto da banco, utilizzabile in ambulatorio o in laboratorio senza personale altamente specializzato.' },
        { t: 'Sensori nanostrutturati', d: 'Semiconduttori prodotti e assemblati interamente in laboratorio, adattabili a diversi tipi di analisi.' },
        { t: 'Biomarcatori gassosi', d: 'Rileva composti organici volatili specifici, prodotti dalle cellule neoplastiche e indicativi della patologia.' },
        { t: 'Test non invasivo', d: 'Analisi in-vitro di un campione di feci — nessuna preparazione invasiva per il paziente.' },
      ],
      imageCaption: 'Render del dispositivo SCENT A1',
    },
    how: {
      kicker: 'Come funziona',
      title: 'Dalla scienza dei gas alla diagnosi',
      lead: 'SCENT A1 è costituito da un nucleo di sensori di gas a semiconduttore che variano la propria resistenza in funzione dei gas con cui entrano in contatto.',
      steps: [
        { n: '01', t: 'Raccolta del campione', d: 'Un campione di feci, conservato in un contenitore standard, viene inserito nello strumento. Nessuna preparazione invasiva richiesta.' },
        { n: '02', t: 'Analisi dei biomarcatori', d: 'I sensori a semiconduttore rilevano i composti organici volatili emessi dalle cellule tumorali — l’impronta chimica del colon.' },
        { n: '03', t: 'Esito clinico', d: 'Il sistema elabora il segnale e restituisce un indicatore della possibile presenza di tumore, a supporto della decisione clinica.' },
      ],
    },
    validation: {
      kicker: 'Validazione clinica',
      title: 'Pubblicato e revisionato',
      lead: 'I risultati clinici di SCENT A1 sono stati pubblicati sulla rivista internazionale Cancers, con una sensibilità dell’84,1% e una specificità dell’82,4%.',
      badges: ['Cancers · MDPI', 'doi:10.3390/cancers12061471', 'Peer-reviewed'],
      cta: 'Leggi la pubblicazione',
      ref: 'CANCERS 2020, 12(6), 1471',
      cardStats: [
        { value: '84,1%', label: 'Sensibilità' },
        { value: '82,4%', label: 'Specificità' },
        { value: '0,91', label: 'AUC' },
        { value: '20+', label: 'Anni di ricerca', sub: 'sensoristica gas' },
      ],
      spinoffTitle: 'Le origini',
      spinoff: 'Nata il 1º aprile 2015 dal Laboratorio Sensori dell’Università di Ferrara — Dipartimento di Fisica e Scienze della Terra.',
    },
    team: {
      kicker: 'Il team',
      title: 'Un comitato scientifico multidisciplinare',
      lead: 'Fisici, chimici, statistici, informatici, biologi e medici con oltre vent’anni di esperienza nella ricerca sui sensori di gas.',
      people: [
        { name: 'Cesare Malagù', role: 'Presidente', img: '/uploads/cesare.png' },
        { name: 'Sandro Gherardi', role: 'Responsabile Tecnico Informatico', img: '/uploads/sandro.png' },
        { name: 'Giulia Zonta', role: 'Responsabile Qualità', img: '/uploads/giulia.png' },
        { name: 'Alessio Giberti', role: 'Esperto Analisi Dati', img: '/uploads/alessio.png' },
        { name: 'Andrea Gaiardo', role: 'Esperto Chimico', img: '/uploads/andrea.png' },
        { name: 'Michele Astolfi', role: 'Lead Auditor', img: '/uploads/mik.png' },
        { name: 'Nicolò Landini', role: 'Responsabile Commerciale', img: '/uploads/nicolo.png' },
        { name: 'Antonio Cimelli', role: 'Responsabile Amministrativo', img: '/uploads/antonio.png' },
        { name: 'Elena Pezzi', role: 'Responsabile Scritture Contabili', img: '/uploads/elena.png' },
      ],
      note: 'In collaborazione con l’Ospedale S. Anna, AUSL e Università di Ferrara e la Casa di Cura Quisisana.',
    },
    contact: {
      kicker: 'Contatti',
      title: 'Scrivici',
      lead: 'Sei una struttura sanitaria o un ricercatore? Richiedi informazioni su SCENT A1 e sulle possibilità di collaborazione, acquisto o noleggio.',
      fields: { name: 'Nome', org: 'Struttura', email: 'Email', message: 'Messaggio' },
      placeholders: { name: 'Mario Rossi', org: 'Ospedale / Ente', email: 'nome@ospedale.it', message: 'Come possiamo aiutarti?' },
      submit: 'Invia richiesta',
      successTitle: 'Richiesta inviata',
      success: 'Grazie. Il team SCENT ti risponderà a breve.',
      whereTitle: 'Dove siamo',
      address: 'Via Quadrifoglio, 11 — 44124 Ferrara',
      phone: '+39 334 7294852',
    },
    footer: {
      tagline: 'Semiconductor-Based Electronic Network for Tumors. Diagnostica oncologica non invasiva basata su sensori a semiconduttore nanostrutturati.',
      columns: [
        { h: 'Prodotto', items: ['SCENT A1', 'SCENT E1', 'Tecnologia', 'Validazione clinica', 'Brevetti'] },
        { h: 'Azienda', items: ['Chi siamo', 'Team scientifico', 'Pubblicazioni', 'Dove siamo'] },
        { h: 'Contatti', items: ['Scrivici', { label: 'Privacy Policy', href: 'https://www.iubenda.com/privacy-policy/781267' }, { label: 'Cookie Policy', href: 'https://www.iubenda.com/privacy-policy/781267/cookie-policy' }, 'Credits'] },
      ],
      legal: '© 2026 SCENT S.r.l. · P.IVA IT0000000000',
      cert: 'CE Marked · ISO 13485',
    },
  },

  en: {
    langLabel: 'EN',
    altLang: 'IT',
    nav: {
      links: [
        { id: 'dispositivo', label: 'Device' },
        { id: 'tecnologia', label: 'Technology' },
        { id: 'validazione', label: 'Validation' },
        { id: 'premi', label: 'Awards' },
        { id: 'stampa', label: 'Press' },
        { id: 'team', label: 'Team' },
      ],
      cta: 'Request a demo',
    },
    hero: {
      badges: ['CE Marked', 'Clinically validated', 'Patented IT · UK · DE'],
      kicker: 'Non-invasive oncology diagnostics',
      titleA: 'Detect earlier.',
      titleB: 'Without being invasive.',
      lead: 'SCENT A1 detects the possible presence of colorectal cancer by analysing the gaseous biomarkers of a fecal sample — using nanostructured semiconductor gas sensors.',
      ctaPrimary: 'Request a demo',
      ctaSecondary: 'How it works',
      imageCaption: 'Photo of the SCENT A1 device',
    },
    press: {
      kicker: 'In the press',
      quote: 'The «artificial nose» invented in Ferrara that aids diagnosis and shortens waiting lists.',
      source: 'Corriere della Sera',
      date: 'April 2025',
      lead: 'The project born at the University of Ferrara has been covered by leading national and local outlets.',
      outlets: [
        { name: 'Corriere della Sera', title: 'The «artificial nose» invented in Ferrara', tag: 'News · Apr 2025' },
        { name: 'Il Resto del Carlino', title: '«Now there’s ScentA1 to prevent in time»', tag: 'Ferrara · Nov 2019' },
        { name: 'Estense.com', title: '«Smelling» to prevent: a new frontier against colon cancer', tag: 'Apr 2025' },
        { name: 'University of Ferrara', title: 'First in Italy to use alternatives to colonoscopy', tag: 'Unife · Nov 2019' },
        { name: 'Il Sole 24 Ore', title: 'Marzotto Prize: Scent’s idea wins', tag: 'Technology · Nov 2015' },
        { name: 'la Repubblica · Bologna', title: 'The test that sniffs out tumours, born at the University of Ferrara', tag: 'News · Nov 2015' },
        { name: 'Corriere Innovazione', title: 'Anti-tumour tests: Scent wins the €300k Marzotto Prize', tag: 'Innovation · Nov 2015' },
        { name: 'La Stampa', title: 'Hi-tech sensors win the Marzotto Prize', tag: 'Economy · Nov 2015' },
        { name: 'La Nuova Ferrara', title: 'Three hundred thousand euro to Scent, the Unife start-up', tag: 'Ferrara · Dec 2015' },
        { name: 'inSalute News', title: 'Colorectal cancer screening: innovative test at Ferrara’s AOU', tag: 'Health · May 2017' },
      ],
    },
    awards: {
      kicker: 'Recognition',
      title: 'Awarded from day one',
      lead: 'Since launching as an innovative start-up, SCENT has been recognised by Italy’s leading prizes for innovation and entrepreneurship.',
      highlight: {
        year: '2015',
        name: 'Gaetano Marzotto Prize',
        body: '1st prize · Milan',
        prize: '€300,000',
        prizeLabel: 'in innovation funding',
        desc: 'SCENT won first prize of the 2015 edition — “innovation at the heart of the new Italian enterprise” — with a grant of three hundred thousand euro.',
      },
      items: [
        { year: '2014', name: 'StartCup Emilia-Romagna', body: 'Winner · PNI selection', note: '3 projects out of 140 admitted to the National Innovation Prize.' },
        { year: '2015', name: 'A New Business Idea', body: '1st prize · Imola', note: 'Best entrepreneurial idea of the 2015 edition.' },
        { year: '2015', name: 'Franci@INNOVazione', body: 'Embassy of France', note: 'Start-Up award presented in Rome by the French Ambassador.' },
        { year: '2015', name: 'INNOVAMI', body: 'Business incubator', note: 'Recognition for technological innovation.' },
        { year: '2016', name: 'CNA “Innovative Thinking”', body: 'Eight Ferrara start-ups', note: 'Recognised among the region’s examples of advanced creativity.' },
        { year: '2013', name: 'UnifeCup', body: 'University of Ferrara', note: 'Business Plan Competition for new high-tech enterprises.' },
      ],
    },
    stats: {
      kicker: 'The numbers',
      items: [
        { value: '84.1%', label: 'Sensitivity', sub: 'validated clinical cohort' },
        { value: '82.4%', label: 'Specificity', sub: 'vs fecal occult blood test' },
        { value: '⅔', label: 'False positives identified', sub: 'fewer needless colonoscopies' },
        { value: '3', label: 'Patents', sub: 'Italy · United Kingdom · Germany' },
      ],
    },
    device: {
      kicker: 'The device',
      title: 'Colorectal screening, rethought',
      lead: 'Used alongside the fecal immunochemical test (FIT), SCENT A1 identifies two-thirds of false positives — reducing unnecessary colonoscopies on healthy patients.',
      features: [
        { t: 'Portable and simple', d: 'A compact benchtop instrument, usable in the clinic or lab without highly specialised staff.' },
        { t: 'Nanostructured sensors', d: 'Semiconductors produced and assembled entirely in-house, adaptable to different types of analysis.' },
        { t: 'Gaseous biomarkers', d: 'Detects specific volatile organic compounds produced by neoplastic cells and indicative of disease.' },
        { t: 'Non-invasive test', d: 'In-vitro analysis of a fecal sample — no invasive preparation for the patient.' },
      ],
      imageCaption: 'Render of the SCENT A1 device',
    },
    how: {
      kicker: 'How it works',
      title: 'From gas science to diagnosis',
      lead: 'SCENT A1 is built around a core of semiconductor gas sensors that change their resistance depending on the gases they come into contact with.',
      steps: [
        { n: '01', t: 'Sample collection', d: 'A fecal sample, kept in a standard container, is loaded into the instrument. No invasive preparation required.' },
        { n: '02', t: 'Biomarker analysis', d: 'The semiconductor sensors detect the volatile organic compounds emitted by tumour cells — the chemical fingerprint of the colon.' },
        { n: '03', t: 'Clinical readout', d: 'The system processes the signal and returns an indicator of possible tumour presence, supporting the clinical decision.' },
      ],
    },
    validation: {
      kicker: 'Clinical validation',
      title: 'Published and peer-reviewed',
      lead: 'SCENT A1’s clinical results were published in the international journal Cancers, with 84.1% sensitivity and 82.4% specificity.',
      badges: ['Cancers · MDPI', 'doi:10.3390/cancers12061471', 'Peer-reviewed'],
      cta: 'Read the publication',
      ref: 'CANCERS 2020, 12(6), 1471',
      cardStats: [
        { value: '84.1%', label: 'Sensitivity' },
        { value: '82.4%', label: 'Specificity' },
        { value: '0.91', label: 'AUC' },
        { value: '20+', label: 'Years of research', sub: 'gas sensing' },
      ],
      spinoffTitle: 'Origins',
      spinoff: 'Founded on 1 April 2015 from the Sensor Laboratory at the University of Ferrara — Department of Physics and Earth Sciences.',
    },
    team: {
      kicker: 'The team',
      title: 'A multidisciplinary scientific committee',
      lead: 'Physicists, chemists, statisticians, computer scientists, biologists and physicians with over twenty years of experience in gas-sensing research.',
      people: [
        { name: 'Cesare Malagù', role: 'President', img: '/uploads/cesare.png' },
        { name: 'Sandro Gherardi', role: 'Head of IT', img: '/uploads/sandro.png' },
        { name: 'Giulia Zonta', role: 'Head of Quality', img: '/uploads/giulia.png' },
        { name: 'Alessio Giberti', role: 'Data Analysis Lead', img: '/uploads/alessio.png' },
        { name: 'Andrea Gaiardo', role: 'Chemistry Lead', img: '/uploads/andrea.png' },
        { name: 'Michele Astolfi', role: 'Lead Auditor', img: '/uploads/mik.png' },
        { name: 'Nicolò Landini', role: 'Head of Sales', img: '/uploads/nicolo.png' },
        { name: 'Antonio Cimelli', role: 'Head of Administration', img: '/uploads/antonio.png' },
        { name: 'Elena Pezzi', role: 'Head of Bookkeeping', img: '/uploads/elena.png' },
      ],
      note: 'In collaboration with S. Anna Hospital, AUSL and University of Ferrara and the Quisisana Clinic.',
    },
    contact: {
      kicker: 'Contact',
      title: 'Get in touch',
      lead: 'Are you a healthcare facility or a researcher? Request information about SCENT A1 and opportunities for collaboration, purchase or rental.',
      fields: { name: 'Name', org: 'Organisation', email: 'Email', message: 'Message' },
      placeholders: { name: 'Mario Rossi', org: 'Hospital / Institution', email: 'name@hospital.com', message: 'How can we help?' },
      submit: 'Send request',
      successTitle: 'Request sent',
      success: 'Thank you. The SCENT team will get back to you shortly.',
      whereTitle: 'Where we are',
      address: 'Via Quadrifoglio, 11 — 44124 Ferrara',
      phone: '+39 334 7294852',
    },
    footer: {
      tagline: 'Semiconductor-Based Electronic Network for Tumors. Non-invasive oncology diagnostics based on nanostructured semiconductor gas sensors.',
      columns: [
        { h: 'Product', items: ['SCENT A1', 'SCENT E1', 'Technology', 'Clinical validation', 'Patents'] },
        { h: 'Company', items: ['About us', 'Scientific team', 'Publications', 'Where we are'] },
        { h: 'Contact', items: ['Write to us', { label: 'Privacy Policy', href: 'https://www.iubenda.com/privacy-policy/781267' }, { label: 'Cookie Policy', href: 'https://www.iubenda.com/privacy-policy/781267/cookie-policy' }, 'Credits'] },
      ],
      legal: '© 2026 SCENT S.r.l. · VAT IT0000000000',
      cert: 'CE Marked · ISO 13485',
    },
  },
};
